### ISSUE TITLE
add tzdata package to be able to set timezone

### ISSUE THREAD

**Issue by fightforlife** [xagaba/snapraid#3]
Hello @xagaba,

I am using this image for quite some time now without problems.
Since in my country there is a daylight savings time I noticed, that cron is fixed to UTC.

It would be realy helpfull if we could include the tzdata package into this image.
That way one could add `"TZ=Europe/London"` to the container run command and everyone would have their correct TZ.

`apk --update add python3 git smartmontools tzdata`

best regards

https://github.com/xagaba/snapraid/pull/4

**Comment by xagaba** [comment]
Updated !
Regards
Xavier

Missatge de Frederik <notifications@github.com> del dia dv., 15 de gen.
2021 a les 21:03:
